autoenc-predict:
  test_dataset: $var(test_folder)
  ckpt: $var(result_folder)/last.ckpt
  predictions: $var(result_folder)/test_prediction
  dataloader:
    batch_size: $var(batch, default=32)
    shuffle: false
    num_workers: $var(num_workers, default=4)
    drop_last: false
    prefecth: $var(prefetch, default=2)
  device: $var(device, default=cuda)
  image_key: image
  image_size: $var(image_size, default=256)
  image_channels: 3
