ec-train:
  train_dataset: $var(train_folder)
  last_ckpt: $var(result_folder)/last.ckpt
  transforms: $import(train_transforms.yaml)
  repeat: 10
  dataloader:
    batch_size: $var(batch, default=32)
    shuffle: true
    num_workers: $var(num_workers, default=4)
    drop_last: false
    prefecth: $var(prefetch, default=2)
  device: $var(device, default="cuda")
  n_epochs: $var(epochs, default=10)
  learning_rate: 0.001
  image_key: image
  image_size: $var(image_size, default=256)
  image_channels: 3
